### ISSUE TITLE
FEATURE:Whip from ZSS

### ISSUE THREAD

**Issue by MrMontes12** [TheRedMajora/DungeonTools#1]
A whip similar to the one in the zeldas sword skills mod. The whip can be used to damage mobs as well as swing from beams (a seperate block). You fling it at a beam and hold down left click to keep it attached, then use it to swing to the opposite side of a hole for example. I always enjoyed this mechanic and thought it was awesome for dungeons, it would be great if you could implement it but if you think it doesn’t fit or it’s too hard then no worries.

**Comment by TheRedMajora** [comment]
ZSS is updating to the newer versions. I don't plan on implementing things that resembles the items in coolAlias' mod.
