### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by iamsewage** [TheRedMajora/DungeonTools#2]
When I use your mod on a standard forge server (Version 14.23.5.2781) it results in a crash.

Crash report: https://pastebin.com/1GK7WHHa

Tested on forge 14.23.5.2781 and just your mod

Wonderful mod, would really like to use it on my server <3

(sorry if I did anything wrong/incorrect when reporting this, first time reporting)

**Comment by TheRedMajora** [comment]
Ahh, that’s strange.
It seems forge ‘expects’ a Server Proxy even if not needed.

I can easily try to fix that, I’ll release a fix tommorow :)

**Comment by iamsewage** [comment]
That's great news :) thanks for your work/mod buddy

**Comment by TheRedMajora** [comment]
Fixed in DungeonTools 2.1.
